if (CMAKE_CXX_COMPILER_ID STREQUAL "Clang" OR CMAKE_CXX_COMPILER_ID STREQUAL "AppleClang")
    include(CoreClangFlags)
elseif(CMAKE_CXX_COMPILER_ID STREQUAL "GNU")
    include(CoreGCCFlags)
elseif(CMAKE_CXX_COMPILER_ID STREQUAL "MSVC")
    include(CoreMSVCFlags)
else()
    message(FATAL_ERROR "Unsupported compiler: ${CMAKE_CXX_COMPILER_ID}")
endif()
