if (CMAKE_CXX_COMPILER_ID STREQUAL "Clang")
    include(ClangFlags)
elseif(CMAKE_CXX_COMPILER_ID STREQUAL "GNU")
    include(GCCFlags)
elseif(CMAKE_CXX_COMPILER_ID STREQUAL "MSVC")
    include(MSVCFlags)
else()
    message(FATAL_ERROR "Unsupported compiler: ${CMAKE_CXX_COMPILER_ID}")
endif()
